# This is a sample build configuration for Other.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
  default:
    - step:
        script:
          - wget https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.deb # Hugo is outdated in apt
          - dpkg -i hugo_0.55.6_Linux-64bit.deb
          - hugo version
          - git submodule update --init # make sure theme is pulled in
          - hugo
        artifacts:
          - public/**
    - step:
        name: Deploy
        deployment: production
        script:
          - pipe: atlassian/scp-deploy:0.3.1
            variables:
              USER: 'lianzadeploy'
              SERVER: 'ssh.lianza.org'
              REMOTE_PATH: '~/public'
              LOCAL_PATH: 'public/*'
              COMMAND: 'chgrp -R pg473580 ~/public && chmod -R 755 ~/public'
